<?php 
    $_items = $this->getReviewsCollection_By_Collection_Filter_By_Categories_Show();
    $_columnCount = $this->getColumnCount();
    $_limit = $this->getLimitCount();
    $_n = count($_items);
    if($_limit == "" || $_limit > $_n){
        $_limit = $_n;
    }    
    $_title = $this->getFrontendTitle();
	$wrapclass = $this->getCustomClass();
    $_showname = $this->showProductName();
    $limit_length = 160;
?>

<div class="block <?php if($wrapclass):?><?php echo $wrapclass;?><?php endif; ?>">
	<?php if($_title!=""): ?>
		<div class="block-title">
			<strong>
				<span><?php echo $_title; ?></span>
			</strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<?php if ($_limit):?>
			<div class="box-collateral box-reviews" id="customer-reviews">
				<?php $i=0; foreach ($_items as $_review):?>
				<?php
					$_product = Mage::getModel('catalog/product')->load($_review['entity_pk_value']); 
				?>
				<?php if ($i++%$_columnCount==0): ?>
					<ul class="products-grid">
				<?php endif ?>
					<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style="<?php echo $this->getItemWidth() ? 'width:'.$this->getItemWidth().'px;' : '' ?> <?php echo $this->getItemHeight() ? 'height:'.$this->getItemHeight().'px;' : '' ?> <?php echo $this->getItemSpacing() ? 'margin-right:'.$this->getItemSpacing().'px;margin-bottom:'.$this->getItemSpacing().'px;' : '' ?>">
						<?php if($_showname=="true"): ?>
							<p class="product-name"><?php echo $this->__('Product Name: ');?></span><a href="<?php echo $_product->getProductUrl() ?>" ><?php echo $_product->getName()?></p>
						<?php endif; ?>
						<p class="title">                    
							<span class="review-title"><?php echo $this->__('Review Title: ');?></span> 
							<a href="<?php echo Mage::getUrl('review/product/list', array('id'=> $_product->getId()));?>"><span class="review-title"><?php echo $this->htmlEscape($_review->getTitle()) ?></span> </a>
						</p>
						
						<p class="by">
							<?php echo $this->__('Review by: <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
						</p>
					 
						<!-- Review Detail -->
						<p class="detail">
							<span><?php echo $this->__('Review Detail: ');?></span>
							<?php if (strlen($_review->getDetail()) > $limit_length) : ?>
								<?php echo trim($this->helper('recentreviewproducts/data')->cutText2($_review->getDetail(),$limit_length)) ?>
							<?php else: ?>
								<?php echo trim($_review->getDetail()) ?>
							<?php endif;?>
						</p>
						<!-- End Review Detail -->
						
						<!--Review Post On -->
						<small class="date"><?php echo $this->__('Posted on : %s', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
						<!--End Review Post On -->
					 </li>
				<?php if ($i%$_columnCount==0 || $i==$_limit): ?>
				</ul>
				<?php endif ?>
				<?php endforeach; ?>
			</div>
		<?php else:?>
			<p class="empty"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php endif; ?>
	</div>
	<script type="text/javascript">
		decorateGeneric($$('ul.products-grid'),['last','first','odd','even']);
	</script>
</div>
