<?php 
    $_items = $this->getReviewsCollection_By_Collection_Filter_By_Categories_Show();
    $limit_length = 160;
    $_limit = $this->getLimitCount();
    $_n = count($_items);
    if($_limit == "" || $_limit > $_n){
        $_limit = $_n;
    }    
    $_title = $this->getFrontendTitle();
	$wrapclass = $this->getCustomClass();
    $_showname = $this->showProductName();
?>
<div class="block<?php if($wrapclass):?><?php echo $wrapclass;?><?php endif; ?>">
	<?php if($_title!=""): ?>
		<div class="block-title">
			<strong>
				<span><?php echo $_title; ?></span>
			</strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<?php if ($_limit):?>
		<div class="box-collateral box-reviews" id="customer-reviews">            
			<?php echo $this->getChildHtml('toolbar') ?>        
			<ul>
				<?php foreach ($_items as $_review):?>
					<?php
						$_product = Mage::getModel('catalog/product')->load($_review['entity_pk_value']);
						
						$_review_info = Mage::getModel('review/review')->getCollection()
						->addStoreFilter(Mage::app()->getStore()->getId())
						->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
						->addFieldToFilter('main_table.review_id', array('eq' =>  $_review['review_id']))
						->addRateVotes()
						;
						
						$_votes = $_review_info->getFirstItem()->getRatingVotes();
					?>
					<li style="<?php echo $this->getItemWidth() ? 'width:'.$this->getItemWidth().'px;' : '' ?> <?php echo $this->getItemHeight() ? 'height:'.$this->getItemHeight().'px;' : '' ?> <?php echo $this->getItemSpacing() ? 'margin-right:'.$this->getItemSpacing().'px;margin-bottom:'.$this->getItemSpacing().'px;' : '' ?>">
					<?php if($_showname=="true"): ?>
						<p class="product-name"><?php echo $this->__('Product Name: ');?></span><a href="<?php echo $_product->getProductUrl() ?>" ><?php echo $_product->getName()?></p>
					<?php endif; ?>
					<p class="title">                    
						<span class="review-title"><?php echo $this->__('Review Title: ');?></span> 
						<a href="<?php echo Mage::getUrl('review/product/list', array('id'=> $_product->getId()));?>"><span class="review-title"><?php echo $this->htmlEscape($_review->getTitle()) ?></span> </a>
					</p>
					
					<p class="by">
						<?php echo $this->__('Review by: <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
					</p>
					 
					<!-- Review Detail Rating Infomation -->
					<?php if (count($_votes)): ?>
					<table class="ratings-table">
						<col width="1" />
						<col />
						<tbody>
							<?php foreach ($_votes as $_vote): ?>
							<tr>
								<th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
								<td>
									<div class="rating-box">
										<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php endif; ?>
					<!-- End Review Detail Rating Infomation -->
							
					<!-- Review Detail -->
					<p class="detail">
						<span><?php echo $this->__('Review Detail: ');?></span>
						<?php if (strlen($_review->getDetail()) > $limit_length) : ?>
							<?php echo trim($this->helper('recentreviewproducts/data')->cutText2($_review->getDetail(),$limit_length)) ?>
						<?php else: ?>
							<?php echo trim($_review->getDetail()) ?>
						<?php endif;?>
					</p>
					<!-- End Review Detail -->
			
					<!--Review Post On -->
						<small class="date"><?php echo $this->__('Posted on : %s', $this->formatDate($_review->getCreatedAt()), 'long') ?></small><br/> <br/>
					<!--End Review Post On -->
					   </li>
				<?php endforeach; ?>
			  </ul>
		</div>
		<?php else:?>
			<p class="empty"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php endif; ?>
	</div>
</div>