<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>
<?php if ($removeUrl = Mage::helper('layerednavigation')->getRemoveUrl($this->_filter)): ?>
<div class="filter-act">
	<a class="btn-remove" href="<?php echo $removeUrl ?>" title="<?php echo $this->__('Clear All') ?>"><?php echo $this->__('Clear All') ?></a>
</div>
<?php endif ?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
		<?php if($_item->isSelected()): echo $_item->getLabel(); ?>
		<?php else: ?>
		<a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
		<?php endif; ?>
		
		<?php if ($this->shouldDisplayProductCount()): ?>
		(<?php echo $_item->getCount() ?>)
		<?php endif; ?>
    </li>
<?php endforeach ?>
</ol>

