<?php
    $itemperslide = $this->getItemPerSlide();
?>

<div id="<?php echo $this->getIdJs();?>" <?php if($cssClass = $this->getData('css_class')):?>class="<?php echo $cssClass;?>"<?php endif;?>>	
	<?php echo $this->getContent();?>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery(window).load(function(){
	if(jQuery('<?php echo $this->getSelector()?>').length){
		jQuery('<?php echo $this->getSelector()?>').addClass('slides');
		jQuery('<?php echo $this->getSelector()?>').parent().csslider({
            move: <?php echo $itemperslide; ?>
            <?php if($this->getData('direction') == 'vertical'):?>,direction : 'vertical'<?php endif; ?>
			<?php if($this->getData('delay')):?>,delay : <?php echo $this->getData('delay')?><?php endif;?>
        });
	}  
});
//]]>
</script>
