<?php 
	$helper = Mage::helper('cms');
    $processor = $helper->getBlockTemplateProcessor();
?>
<div class="tabs_wrapper">
	<ul class="tabs_control">
		<?php for($i = 1;$i <= 10;$i++):?>
			<?php if($this->getTitleTab($i)):?>
			<li>
				<a href="#tab_<?php echo $i;?>"><?php echo $this->getTitleTab($i)?></a>
			</li>
			<?php endif;?>
		<?php endfor;?>
	</ul>
	<div class="tab_content">
		<?php for($i = 1;$i <= 10;$i++):?>
			<?php if($this->getTitleTab($i)):?>
			<div class="tab-item content_tab_<?php echo $i;?>">
				<?php 
					//Show Static Block 
					echo $processor->filter($this->getStaticBlock($i));
					//Show Widget Instance 
					echo $processor->filter($this->getWidgetInstance($i));
				?>	
			</div>	
			<?php endif;?>
		<?php endfor;?>
	</div>
</div>