<?php
/**
 * Mage SMS - SMS notification & SMS marketing
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the BSD 3-Clause License
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/BSD-3-Clause
 *
 * @category    TOPefekt
 * @package     TOPefekt_Magesms
 * @copyright   Copyright (c) 2012-2015 TOPefekt s.r.o. (http://www.mage-sms.com)
 * @license     http://opensource.org/licenses/BSD-3-Clause
 */
?><?php if ($this->getOptoutMarketingActive()): ?><div class="dashboard"><div class="box"><div class="box-account box-info"><div class="box-title"><h3><?php echo $this->__('Marketing SMS'); ?>: <?php echo $this->getOptoutMarketing() ? $this->__('Yes') : $this->__('No');?></h3><a href="<?php echo $this->getUrl('magesms/marketing'); ?>"><?php echo $this->getOptoutMarketing() ? $this->__('Disable') : $this->__('Enable');?></a></div></div></div></div><?php endif; ?>