<li class="fields">
    <div class="field">
        <label for="giantpoints_referral">
            <?php
            echo $this->__('Referral E-mail or Code');
            ?>
        </label>

        <div class="input-box">
            <input type="text" name="giantpoints_referral" id="giantpoints_referral" class="input-text"
                   value="<?php echo $this->getCurrentAffiliate(); ?>"/>
        </div>
    </div>
</li>